package io.github.zonnedev.ocpp.v201;

import io.github.zonnedev.ocpp.api.OcppRequest;

/** Exhaustive v201 request payload family. */
public sealed interface Ocpp201Request extends OcppRequest
  permits io.github.zonnedev.ocpp.v201.model.AuthorizeRequest,
  io.github.zonnedev.ocpp.v201.model.BootNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.CancelReservationRequest,
  io.github.zonnedev.ocpp.v201.model.CertificateSignedRequest,
  io.github.zonnedev.ocpp.v201.model.ChangeAvailabilityRequest,
  io.github.zonnedev.ocpp.v201.model.ClearCacheRequest,
  io.github.zonnedev.ocpp.v201.model.ClearChargingProfileRequest,
  io.github.zonnedev.ocpp.v201.model.ClearDisplayMessageRequest,
  io.github.zonnedev.ocpp.v201.model.ClearVariableMonitoringRequest,
  io.github.zonnedev.ocpp.v201.model.ClearedChargingLimitRequest,
  io.github.zonnedev.ocpp.v201.model.CostUpdatedRequest,
  io.github.zonnedev.ocpp.v201.model.CustomerInformationRequest,
  io.github.zonnedev.ocpp.v201.model.DataTransferRequest,
  io.github.zonnedev.ocpp.v201.model.DeleteCertificateRequest,
  io.github.zonnedev.ocpp.v201.model.FirmwareStatusNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.Get15118EVCertificateRequest,
  io.github.zonnedev.ocpp.v201.model.GetBaseReportRequest,
  io.github.zonnedev.ocpp.v201.model.GetCertificateStatusRequest,
  io.github.zonnedev.ocpp.v201.model.GetChargingProfilesRequest,
  io.github.zonnedev.ocpp.v201.model.GetCompositeScheduleRequest,
  io.github.zonnedev.ocpp.v201.model.GetDisplayMessagesRequest,
  io.github.zonnedev.ocpp.v201.model.GetInstalledCertificateIdsRequest,
  io.github.zonnedev.ocpp.v201.model.GetLocalListVersionRequest,
  io.github.zonnedev.ocpp.v201.model.GetLogRequest,
  io.github.zonnedev.ocpp.v201.model.GetMonitoringReportRequest,
  io.github.zonnedev.ocpp.v201.model.GetReportRequest,
  io.github.zonnedev.ocpp.v201.model.GetTransactionStatusRequest,
  io.github.zonnedev.ocpp.v201.model.GetVariablesRequest,
  io.github.zonnedev.ocpp.v201.model.HeartbeatRequest,
  io.github.zonnedev.ocpp.v201.model.InstallCertificateRequest,
  io.github.zonnedev.ocpp.v201.model.LogStatusNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.MeterValuesRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyChargingLimitRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyCustomerInformationRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyDisplayMessagesRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyEVChargingNeedsRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyEVChargingScheduleRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyEventRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyMonitoringReportRequest,
  io.github.zonnedev.ocpp.v201.model.NotifyReportRequest,
  io.github.zonnedev.ocpp.v201.model.PublishFirmwareRequest,
  io.github.zonnedev.ocpp.v201.model.PublishFirmwareStatusNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.ReportChargingProfilesRequest,
  io.github.zonnedev.ocpp.v201.model.RequestStartTransactionRequest,
  io.github.zonnedev.ocpp.v201.model.RequestStopTransactionRequest,
  io.github.zonnedev.ocpp.v201.model.ReservationStatusUpdateRequest,
  io.github.zonnedev.ocpp.v201.model.ReserveNowRequest,
  io.github.zonnedev.ocpp.v201.model.ResetRequest,
  io.github.zonnedev.ocpp.v201.model.SecurityEventNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.SendLocalListRequest,
  io.github.zonnedev.ocpp.v201.model.SetChargingProfileRequest,
  io.github.zonnedev.ocpp.v201.model.SetDisplayMessageRequest,
  io.github.zonnedev.ocpp.v201.model.SetMonitoringBaseRequest,
  io.github.zonnedev.ocpp.v201.model.SetMonitoringLevelRequest,
  io.github.zonnedev.ocpp.v201.model.SetNetworkProfileRequest,
  io.github.zonnedev.ocpp.v201.model.SetVariableMonitoringRequest,
  io.github.zonnedev.ocpp.v201.model.SetVariablesRequest,
  io.github.zonnedev.ocpp.v201.model.SignCertificateRequest,
  io.github.zonnedev.ocpp.v201.model.StatusNotificationRequest,
  io.github.zonnedev.ocpp.v201.model.TransactionEventRequest,
  io.github.zonnedev.ocpp.v201.model.TriggerMessageRequest,
  io.github.zonnedev.ocpp.v201.model.UnlockConnectorRequest,
  io.github.zonnedev.ocpp.v201.model.UnpublishFirmwareRequest,
  io.github.zonnedev.ocpp.v201.model.UpdateFirmwareRequest {
}
