package io.github.zonnedev.ocpp.v201;

import io.github.zonnedev.ocpp.api.OcppResponse;

/** Exhaustive v201 response payload family. */
public sealed interface Ocpp201Response extends OcppResponse
  permits io.github.zonnedev.ocpp.v201.model.AuthorizeResponse,
  io.github.zonnedev.ocpp.v201.model.BootNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.CancelReservationResponse,
  io.github.zonnedev.ocpp.v201.model.CertificateSignedResponse,
  io.github.zonnedev.ocpp.v201.model.ChangeAvailabilityResponse,
  io.github.zonnedev.ocpp.v201.model.ClearCacheResponse,
  io.github.zonnedev.ocpp.v201.model.ClearChargingProfileResponse,
  io.github.zonnedev.ocpp.v201.model.ClearDisplayMessageResponse,
  io.github.zonnedev.ocpp.v201.model.ClearVariableMonitoringResponse,
  io.github.zonnedev.ocpp.v201.model.ClearedChargingLimitResponse,
  io.github.zonnedev.ocpp.v201.model.CostUpdatedResponse,
  io.github.zonnedev.ocpp.v201.model.CustomerInformationResponse,
  io.github.zonnedev.ocpp.v201.model.DataTransferResponse,
  io.github.zonnedev.ocpp.v201.model.DeleteCertificateResponse,
  io.github.zonnedev.ocpp.v201.model.FirmwareStatusNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.Get15118EVCertificateResponse,
  io.github.zonnedev.ocpp.v201.model.GetBaseReportResponse,
  io.github.zonnedev.ocpp.v201.model.GetCertificateStatusResponse,
  io.github.zonnedev.ocpp.v201.model.GetChargingProfilesResponse,
  io.github.zonnedev.ocpp.v201.model.GetCompositeScheduleResponse,
  io.github.zonnedev.ocpp.v201.model.GetDisplayMessagesResponse,
  io.github.zonnedev.ocpp.v201.model.GetInstalledCertificateIdsResponse,
  io.github.zonnedev.ocpp.v201.model.GetLocalListVersionResponse,
  io.github.zonnedev.ocpp.v201.model.GetLogResponse,
  io.github.zonnedev.ocpp.v201.model.GetMonitoringReportResponse,
  io.github.zonnedev.ocpp.v201.model.GetReportResponse,
  io.github.zonnedev.ocpp.v201.model.GetTransactionStatusResponse,
  io.github.zonnedev.ocpp.v201.model.GetVariablesResponse,
  io.github.zonnedev.ocpp.v201.model.HeartbeatResponse,
  io.github.zonnedev.ocpp.v201.model.InstallCertificateResponse,
  io.github.zonnedev.ocpp.v201.model.LogStatusNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.MeterValuesResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyChargingLimitResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyCustomerInformationResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyDisplayMessagesResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyEVChargingNeedsResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyEVChargingScheduleResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyEventResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyMonitoringReportResponse,
  io.github.zonnedev.ocpp.v201.model.NotifyReportResponse,
  io.github.zonnedev.ocpp.v201.model.PublishFirmwareResponse,
  io.github.zonnedev.ocpp.v201.model.PublishFirmwareStatusNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.ReportChargingProfilesResponse,
  io.github.zonnedev.ocpp.v201.model.RequestStartTransactionResponse,
  io.github.zonnedev.ocpp.v201.model.RequestStopTransactionResponse,
  io.github.zonnedev.ocpp.v201.model.ReservationStatusUpdateResponse,
  io.github.zonnedev.ocpp.v201.model.ReserveNowResponse,
  io.github.zonnedev.ocpp.v201.model.ResetResponse,
  io.github.zonnedev.ocpp.v201.model.SecurityEventNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.SendLocalListResponse,
  io.github.zonnedev.ocpp.v201.model.SetChargingProfileResponse,
  io.github.zonnedev.ocpp.v201.model.SetDisplayMessageResponse,
  io.github.zonnedev.ocpp.v201.model.SetMonitoringBaseResponse,
  io.github.zonnedev.ocpp.v201.model.SetMonitoringLevelResponse,
  io.github.zonnedev.ocpp.v201.model.SetNetworkProfileResponse,
  io.github.zonnedev.ocpp.v201.model.SetVariableMonitoringResponse,
  io.github.zonnedev.ocpp.v201.model.SetVariablesResponse,
  io.github.zonnedev.ocpp.v201.model.SignCertificateResponse,
  io.github.zonnedev.ocpp.v201.model.StatusNotificationResponse,
  io.github.zonnedev.ocpp.v201.model.TransactionEventResponse,
  io.github.zonnedev.ocpp.v201.model.TriggerMessageResponse,
  io.github.zonnedev.ocpp.v201.model.UnlockConnectorResponse,
  io.github.zonnedev.ocpp.v201.model.UnpublishFirmwareResponse,
  io.github.zonnedev.ocpp.v201.model.UpdateFirmwareResponse {
}
